name: CI

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Run a one-line script
      run: echo "writing github object to /tmp/gitActionResult.log"
    - name: Run a multi-line script
      run: echo "${{toJSON(github)}}" >> /tmp/gitActionResult.log
