name: CI

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Run a one-line script
      run: echo ${{github}}
    - name: Run a multi-line script
      run: echo ${{github}} >> /tmp/gitActionResult.log
